# Generated by Django 3.2.4 on 2021-06-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("complete", models.BooleanField(default=False)),
                ("deadline", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
